/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Class;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Phan Tran Minh Tam
 */
public class DSCuaHang {
    public Connection con;
    public ArrayList<CuaHang> layDanhSachCuaHang()
    {
        ArrayList<CuaHang> ds = new ArrayList<>();
        try {
            
            
            KetNoi conn = new KetNoi();
            conn.ketNoi();
            //KetNoi();
            String sql = "Select * FROM LOAICH WHERE TRANGTHAI=0";
            Statement st = conn.ketNoi().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                CuaHang n = new CuaHang();
                n.mach = rs.getString("MACH");
                n.Tench= rs.getString("TENCH");
                n.Ghichu = rs.getString("GHICHU");
                ds.add(n);
 
            }
            //n.con.close();
            conn.ketNoi().close();
        } catch (SQLException ex) {
            Logger.getLogger(DSCuaHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ds;
    }
//    public ArrayList<CuaHang> timKiemCuaHang(String giatri)
//    {
//        ArrayList<CuaHang> ds = new ArrayList<>();
//        try {
//            
//            
//            KetNoi conn = new KetNoi();
//            conn.ketNoi();
//            //KetNoi();
////            String sql = "Select * FROM DANHMUCSP";
////            Statement st = conn.ketNoi().createStatement();
//            CallableStatement st = conn.ketNoi().prepareCall("{call timKiemDanhMuc (?)}");
//            st.setString(1,giatri);
//            ResultSet rs = st.executeQuery();
//            while(rs.next())
//            {
//                CuaHang n = new CuaHang();
//                n.mach = rs.getString("MACH");
//                n.Tench= rs.getString("TENCH");
//                n.Ghichu = rs.getString("GHICHU");
//                ds.add(n);
// 
//            }
//            //n.con.close();
//            conn.ketNoi().close();
//        } catch (SQLException ex) {
//            Logger.getLogger(DSCuaHang.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return ds;
//    }
//    public String SinhMaDanhMuc() {
//    String maloai = ""; // Default value
//
//    try (Connection connection = new KetNoi().ketNoi();
//         CallableStatement st = connection.prepareCall("{call sinhma_madmlonnhat}")) { // Call the stored procedure
//
//        ResultSet rs = st.executeQuery();
//        if (rs.next()) {
//            String ma = rs.getString("MALOAI"); // Assuming the column name is "MAKH"
//            String so = ma.substring(1);
//            maloai = "L" + String.format("%02d", Integer.parseInt(so) + 1);
//        }
//    } catch (SQLException ex) {
//        Logger.getLogger(DSDanhMuc.class.getName()).log(Level.SEVERE, "Error generating customer code", ex);
//        // Optional: Throw a custom exception
//    }
//
//    return maloai;
//}
//    public void themDanhMuc(DanhMuc danhmuc) {
//    try {
////        // Sinh mã danh mục tự động dựa vào tên danh mục
////        String autoGeneratedMaDanhMuc = generateMaDanhMuc(danhmuc.getTenDanhMuc());
//
//        KetNoi conn = new KetNoi();
//        conn.ketNoi();
//        CallableStatement st = conn.ketNoi().prepareCall("{call insert_loaisp (?,?)}");
//        st.setString(1, danhmuc.getMaloai() ); // Sử dụng mã danh mục tự động
//        st.setString(2, danhmuc.getTenloai());
//        st.executeUpdate();
//        JOptionPane.showMessageDialog(null, "Thêm thành công");
//        conn.ketNoi().close();
//    } catch (SQLException ex) {
//        Logger.getLogger(DSDanhMuc.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    public String getMaCH() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
