/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Class.CuaHang;
import Class.DSCuaHang;
import Class.DSDanhMuc;
import Class.DSSanPham;
import Class.DanhMuc;
import Class.DsNhaCC;
import Class.KhachHang;
import Class.NhaCungCap;
import Class.SanPham;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Triss    
 */
public class Form_NhapNhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form Form_NhapNhaCungCap
     */
    DSSanPham sp;
    DSDanhMuc dm;
    DsNhaCC ncc;
    DSCuaHang ch;
    
    ArrayList<NhaCungCap> dsNCC;
    ArrayList<SanPham> dsSP;
    ArrayList<DanhMuc> dsDanhMuc;
    ArrayList<CuaHang> dsCuaHang;
    String mach;
    int vitri = 0;
    int flag = 0;
    private final int maNCCMaxLength = 10; // Độ dài tối đa cho mã NCC
    private final int tenNCCLength = 50; // Độ dài tối đa cho tên NCC
    private final int diaChiMaxLength = 20; // Độ dài tối đa cho địa chỉ

    public Form_NhapNhaCungCap() {
        initComponents();
        sp = new DSSanPham();
        dm = new DSDanhMuc();
        ncc = new DsNhaCC();
        ch = new DSCuaHang();
        
        dsSP = sp.layDanhSachSanPham();
        dsDanhMuc = dm.layDanhSachDanhMuc();
        dsNCC = ncc.layDanhSachNCC();
        dsCuaHang = ch.layDanhSachCuaHang();
        
        hienThiComboBoxDanhMuc(dsDanhMuc,Cbo_TenDM);
        hienThiComboboxSP(dsCuaHang, cbo_tenCh);
        hienThiTextBox(vitri);
        hienThiTable();
        //RangBuocTxt();
        anHienTextbox(false);
        //initializeMaNCCField();
    }
    public NhaCungCap getNCCMoiNhat() {
        return dsNCC.get(dsNCC.size() - 1);
    }
    public boolean tonTaiMaNCC(String maNCC) {
        for (NhaCungCap ncc : dsNCC) {
            if (ncc.getMaNCC().equals(maNCC)) {
                return true;
            }
        }
        return false;
    }
    
//    public boolean coTenGiongNhau(String tenNCC) {
//        for (NhaCungCap ncc : dsNCC) {
//            if (ncc.getTenNCC().trim().equalsIgnoreCase(tenNCC.trim())) {
//                return true;
//            }
//        }
//        return false;
//    }
    
//    private String generateMaNCC() {
//        String autoGeneratedMaNCC = "NCC" + UUID.randomUUID().toString().substring(0, 6);
//        return autoGeneratedMaNCC;
//    }

//    private void initializeMaNCCField() {
//        String autoGeneratedMaNCC = generateMaNCC();
//        txt_MaNCC.setText(autoGeneratedMaNCC);
//    }

    private void RangBuocTxt() {
        txt_TenNCC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String tenNCC = txt_TenNCC.getText().trim();
                if (tenNCC.isEmpty() && tenNCC.length() <= tenNCCLength) {
                    JOptionPane.showMessageDialog(null, "Tên không được để trống và không vượt quá " + tenNCCLength + " ký tự.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    txt_TenNCC.setText("");
                    txt_TenNCC.requestFocusInWindow();
                }

            }
        });

        txt_DiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (txt_DiaChi.getText().length() >= diaChiMaxLength) {
                    evt.consume();
                }
            }
        });

        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
                    evt.consume();
                }
                if (txt_SDT.getText().length() >= 10 || (txt_SDT.getText().isEmpty() && c != '0')) {
                    evt.consume();
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số 0 đầu tiên và bạn chỉ nhập được 10 số thôi!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            }
        });

        txt_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
                Pattern pattern = Pattern.compile(emailPattern);
                Matcher matcher = pattern.matcher(txt_Email.getText());
                if (!matcher.matches()) {
                    JOptionPane.showMessageDialog(null, "Email không hợp lệ. Vui lòng nhập lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    txt_Email.requestFocusInWindow();
                }
            }
        });
    }
    
    private void hienThiComboBoxDanhMuc(ArrayList<DanhMuc> danhMuc, JComboBox<String> cbo){
        //cbo.removeAllItems();
        for (DanhMuc s:danhMuc)
        {
            cbo.addItem(s.getTenloai());
        }
    }
    
    private void hienThiComboboxSP(ArrayList<CuaHang> ch, JComboBox<String> cbo){
        //cbo.removeAllItems();
        for (CuaHang chang :ch)
        {
            cbo.addItem(chang.getTench());
        }
    }
    int TimViTriCuaHang(ArrayList<CuaHang> ch , String giatri){
        for (int i = 0 ;i<ch.size();i++)
            if(ch.get(i).getMach().equalsIgnoreCase(giatri))
                return i;
        return -1;
    }
    int TimViTriLoai(ArrayList<DanhMuc> dm , String giatri){
        for (int i = 0 ;i<dm.size();i++)
            if(dm.get(i).getMaloai().equalsIgnoreCase(giatri))
                return i;
        return -1;
    }
    private void hienThiTextBox(int vitri) {
    NhaCungCap n = dsNCC.get(vitri);
    txt_MaNCC.setText(n.getMaNCC());
    txt_TenNCC.setText(n.getTenNCC());
    txt_DiaChi.setText(n.getDiaChi());
    txt_Email.setText(n.getEmail());
    txt_SDT.setText(String.valueOf(n.getSDT()));

        String mach = n.getMaCH();
        String maloai = n.getMaloai();
        int vt1 = TimViTriLoai(dsDanhMuc, maloai);
        int vt = TimViTriCuaHang(dsCuaHang, mach);
        if(vt!= -1)
        cbo_tenCh.setSelectedIndex(vt);
        if(vt1!=-1)
        Cbo_TenDM.setSelectedIndex(vt1);
}
    private void hienThiTable() {
    String[] Header = {"Mã NCC", "Tên NCC", "Địa chỉ", "SĐT", "Email","Mã Cửa hàng","Mã Loại"};
    DefaultTableModel model = new DefaultTableModel(Header, 0);
    
    // Kiểm tra xem dsNCC có tồn tại và không rỗng
    if (dsNCC != null && !dsNCC.isEmpty()) {
        for (NhaCungCap n : dsNCC) {
            Object[] rowData = {n.getMaNCC(), n.getTenNCC(), n.getDiaChi(), n.getSDT(), n.getEmail(),n.getMaCH(),n.getMaloai()};
            model.addRow(rowData);
        }
    }
    tbl_NhaCC.fixTable(jScrollPane1);
    tbl_NhaCC.setModel(model);
    
    // Kiểm tra và đặt lại lựa chọn hàng nếu vitri hợp lệ
    if (vitri >= 0 && vitri < model.getRowCount()) {
        tbl_NhaCC.setRowSelectionInterval(vitri, vitri);
    }
}
    private void xoaTextBox()
    {
        txt_MaNCC.setText("");
        txt_TenNCC.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        txt_Email.setText("");
        txt_TimKiem.setText("");
    }
    
    private void anHienTextbox(boolean t)
    {
        txt_MaNCC.setEnabled(t);
        txt_TenNCC.setEnabled(t);
        txt_DiaChi.setEnabled(t);
        txt_SDT.setEnabled(t);
        txt_Email.setEnabled(t);
    
    }
    
    private void anHienButton(boolean t)
    {
        btn_Them.setEnabled(t);
        btn_Sua.setEnabled(t);
        btn_Xoa.setEnabled(t);
        btn_Luu.setEnabled(!t);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new swing.round.RoundPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_MaDanhMuc = new javax.swing.JLabel();
        lb_TenDanhMuc = new javax.swing.JLabel();
        lb_GhiChu = new javax.swing.JLabel();
        btn_Reset = new component.Button();
        btn_Sua = new component.Button();
        btn_Xoa = new component.Button();
        jScrollPane21 = new javax.swing.JScrollPane();
        txt_TimKiem = new javax.swing.JTextPane();
        btn_TimKiem = new component.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhaCC = new swing.table.Table();
        lb_GhiChu1 = new javax.swing.JLabel();
        lb_GhiChu2 = new javax.swing.JLabel();
        btn_Them = new component.Button();
        btn_Luu = new component.Button();
        txt_SDT = new javax.swing.JTextField();
        txt_MaNCC = new javax.swing.JTextField();
        txt_TenNCC = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        lb_TenDanhMuc1 = new javax.swing.JLabel();
        lb_MaDanhMuc1 = new javax.swing.JLabel();
        cbo_tenCh = new javax.swing.JComboBox<>();
        Cbo_TenDM = new javax.swing.JComboBox<>();

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN NHÀ CUNG CẤP");

        lb_MaDanhMuc.setBackground(new java.awt.Color(0, 0, 255));
        lb_MaDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_MaDanhMuc.setForeground(new java.awt.Color(255, 0, 51));
        lb_MaDanhMuc.setText("Mã NCC:");

        lb_TenDanhMuc.setBackground(new java.awt.Color(0, 0, 255));
        lb_TenDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_TenDanhMuc.setForeground(new java.awt.Color(255, 0, 51));
        lb_TenDanhMuc.setText("Tên NCC:");

        lb_GhiChu.setBackground(new java.awt.Color(0, 0, 255));
        lb_GhiChu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_GhiChu.setForeground(new java.awt.Color(255, 0, 51));
        lb_GhiChu.setText("Số điện thoại:");

        btn_Reset.setBackground(new java.awt.Color(238, 230, 255));
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_refesh.png"))); // NOI18N
        btn_Reset.setText("Làm mới");
        btn_Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(238, 230, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_edit.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(238, 230, 255));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_delete.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        txt_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane21.setViewportView(txt_TimKiem);

        btn_TimKiem.setBackground(new java.awt.Color(238, 230, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_search.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        tbl_NhaCC.setBackground(new java.awt.Color(204, 204, 204));
        tbl_NhaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên NCC", "SĐT", "Địa chỉ", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_NhaCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_NhaCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhaCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_NhaCC);

        lb_GhiChu1.setBackground(new java.awt.Color(0, 0, 255));
        lb_GhiChu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_GhiChu1.setForeground(new java.awt.Color(255, 0, 51));
        lb_GhiChu1.setText("Địa chỉ:");

        lb_GhiChu2.setBackground(new java.awt.Color(0, 0, 255));
        lb_GhiChu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_GhiChu2.setForeground(new java.awt.Color(255, 0, 51));
        lb_GhiChu2.setText("Email:");

        btn_Them.setBackground(new java.awt.Color(238, 230, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_add.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Luu.setBackground(new java.awt.Color(238, 230, 255));
        btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_save.png"))); // NOI18N
        btn_Luu.setText("Lưu");
        btn_Luu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        txt_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SDTKeyPressed(evt);
            }
        });

        txt_MaNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_TenNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TenNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_TenNCCKeyPressed(evt);
            }
        });

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_DiaChiKeyPressed(evt);
            }
        });

        lb_TenDanhMuc1.setBackground(new java.awt.Color(0, 0, 255));
        lb_TenDanhMuc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_TenDanhMuc1.setForeground(new java.awt.Color(255, 0, 51));
        lb_TenDanhMuc1.setText("Tên danh mục:");

        lb_MaDanhMuc1.setBackground(new java.awt.Color(0, 0, 255));
        lb_MaDanhMuc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_MaDanhMuc1.setForeground(new java.awt.Color(255, 0, 51));
        lb_MaDanhMuc1.setText("Tên cửa hàng:");

        cbo_tenCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tenChActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_TenDanhMuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_MaDanhMuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_TenDanhMuc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_MaDanhMuc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_tenCh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cbo_TenDM, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(lb_GhiChu2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_GhiChu, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_GhiChu1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_SDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addGap(363, 363, 363))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(btn_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_GhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_GhiChu2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_MaDanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_tenCh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_TenDanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbo_TenDM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_MaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_TenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        xoaTextBox();
        
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        flag = 2;
        anHienTextbox(true);
        anHienButton(false);
        txt_MaNCC.setEnabled(false);
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
       // Hide buttons
        flag = 3 ;
        anHienButton(false);
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
         if (txt_TimKiem.getText()!=null)
        {
            dsNCC = ncc.timKiemNhaCungCap(txt_TimKiem.getText());
            vitri = 0;
            hienThiTable();
            hienThiTextBox(vitri);
        }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        flag = 1;
        xoaTextBox();
        int vitri = cbo_tenCh.getSelectedIndex();
        CuaHang c = dsCuaHang.get(vitri);
        // Mã danh mục sẽ không thể chỉnh sửa trong chế độ sửa
        txt_MaNCC.setText(ncc.SinhMaNCC(c.getMach()));
//        txt_MaNCC.setText(ncc.SinhMaNhaCC());
        //initializeMaNCCField();
        anHienTextbox(true);
        anHienButton(false);
        RangBuocTxt();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void tbl_NhaCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhaCCMouseClicked
      vitri = tbl_NhaCC.getSelectedRow();
        hienThiTextBox(vitri);
    }//GEN-LAST:event_tbl_NhaCCMouseClicked
    
    private NhaCungCap convertTextbox_to_Obj()
    {   
        int vtch = cbo_tenCh.getSelectedIndex();
        CuaHang c =dsCuaHang.get(vtch);
        int vtloai = Cbo_TenDM.getSelectedIndex();
        DanhMuc dm =dsDanhMuc.get(vtloai);
        NhaCungCap nhacungcap = new NhaCungCap(txt_MaNCC.getText(),txt_TenNCC.getText(),txt_DiaChi.getText(),txt_SDT.getText(),txt_Email.getText(),c.getMach(),dm.getMaloai());
        return nhacungcap;
    }
    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
     // Convert textbox data to object
    NhaCungCap nhacungcap = convertTextbox_to_Obj();
    boolean hopLe = true;

    if (!kiemTraRangBuoc(nhacungcap)) {
        hopLe = false;
        JOptionPane.showMessageDialog(this, "Ràng buộc không hợp lệ. Vui lòng kiểm tra lại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }

    if (hopLe) {
        if (flag == 1) {
            if (ncc.themNCC(nhacungcap)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm không thành công. Vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else if (flag == 2) {
            if (ncc.capNhatNCC(nhacungcap)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật không thành công. Vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else if (flag == 3) {
                int kq= JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.YES_NO_CANCEL_OPTION);
                if(kq==JOptionPane.YES_OPTION) {
                    ncc.xoaNCC(nhacungcap);
                    
                }
         }
        
        // Refresh data after successful operation
        flag = 0;
        ncc = new DsNhaCC();
        dsNCC = ncc.layDanhSachNCC();
        hienThiTextBox(vitri);
        
        // Update table
        hienThiTable();

        btn_Luu.setEnabled(false);
        btn_Them.setEnabled(true);
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);
    }
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void txt_TenNCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TenNCCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_SDT.requestFocus();
        }
    }//GEN-LAST:event_txt_TenNCCKeyPressed

    private void txt_SDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDTKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_DiaChi.requestFocus();
        }
    }//GEN-LAST:event_txt_SDTKeyPressed

    private void txt_DiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DiaChiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_Email.requestFocus();
        }
    }//GEN-LAST:event_txt_DiaChiKeyPressed

    private void cbo_tenChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tenChActionPerformed
        // TODO add your handling code here:
//        int vt = cbo_tenCh.getSelectedIndex();
//        if(vt !=-1){
//            CuaHang c = dsCuaHang.get(vt);
//            dsDanhMuc = dm.DanhSachNCC_Theocuahang(mach);
//        }
    }//GEN-LAST:event_cbo_tenChActionPerformed
    private boolean kiemTraRangBuoc(NhaCungCap nhacungcap) {
    // Kiểm tra null
    if (nhacungcap == null || nhacungcap.getTenNCC() == null || nhacungcap.getSDT() == null || nhacungcap.getEmail() == null) {
        return false;
    }

    // Kiểm tra ràng buộc
    String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    String tenNCC = nhacungcap.getTenNCC().trim();
    String sdt = nhacungcap.getSDT().trim();
    String email = nhacungcap.getEmail().trim();

    if (tenNCC.isEmpty() || sdt.isEmpty() || email.isEmpty() || !email.matches(emailPattern)) {
        return false;
    }
    
    return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbo_TenDM;
    private component.Button btn_Luu;
    private component.Button btn_Reset;
    private component.Button btn_Sua;
    private component.Button btn_Them;
    private component.Button btn_TimKiem;
    private component.Button btn_Xoa;
    private javax.swing.JComboBox<String> cbo_tenCh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JLabel lb_GhiChu;
    private javax.swing.JLabel lb_GhiChu1;
    private javax.swing.JLabel lb_GhiChu2;
    private javax.swing.JLabel lb_MaDanhMuc;
    private javax.swing.JLabel lb_MaDanhMuc1;
    private javax.swing.JLabel lb_TenDanhMuc;
    private javax.swing.JLabel lb_TenDanhMuc1;
    private swing.round.RoundPanel roundPanel1;
    private swing.table.Table tbl_NhaCC;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNCC;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNCC;
    private javax.swing.JTextPane txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
