/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Class.DSKhachHang;
import Class.KhachHang;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Triss
 */
public class Form_NhapKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form Form_NhapKhachHang
     */
    DSKhachHang kh;
    ArrayList<KhachHang> dsKH;
    int vitri = 0;
    int flag = 0;
    private final int maKHMaxLength = 10; // Độ dài tối đa cho mã NCC
    private final int tenKHLength = 50; // Độ dài tối đa cho tên NCC
    private final int diaChiMaxLength = 20; // Độ dài tối đa cho địa chỉ

    public Form_NhapKhachHang() {
        initComponents();
        kh = new DSKhachHang();
        dsKH = kh.layDanhSachKhachHang();
        hienThiTextBox(vitri);
        hienThiTable();
        //RangBuocTxt();
        anHienTextbox(false);
        anHienButton(true);
        //initializeMaKHField();
    }
    
//    public boolean tonTaiMaKH(String maKh) {
//        for (KhachHang kh : dsKH) {
//            if (kh.getMaKH().equals(maKh)) {
//                return true;
//            }
//        }
//        return false;
//    }
    
//    public boolean coTenGiongNhau(String tenKH) {
//        for (KhachHang kh : dsKH) {
//            if (kh.getMaKH().trim().equalsIgnoreCase(tenKH.trim())) {
//                return true;
//            }
//        }
//        return false;
//    }

    public KhachHang getKhachHangMoiNhat() {
        return dsKH.get(dsKH.size() - 1);
    }
    
    private String generateMaKH() {
        String autoGeneratedMaKH = "KH" + UUID.randomUUID().toString().substring(0, 6);
        return autoGeneratedMaKH;
    }

    private void initializeMaKHField() {
        String autoGeneratedMaNCC = generateMaKH();
        txt_MaKH.setText(autoGeneratedMaNCC);
    }

    private void RangBuocTxt() {
        txt_TenKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String tenKH = txt_TenKH.getText().trim();
                if (tenKH.isEmpty() && tenKH.length() <= tenKHLength) {
                    JOptionPane.showMessageDialog(null, "Tên không được để trống và không vượt quá " + tenKHLength + " ký tự.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    txt_TenKH.setText("");
                    txt_TenKH.requestFocusInWindow();
                }
            }
        });

        txt_DiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (txt_DiaChi.getText().length() >= diaChiMaxLength) {
                    evt.consume();
                }
            }
        });

        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
                    evt.consume();
                }
                if (txt_SDT.getText().length() >= 10 || (txt_SDT.getText().isEmpty() && c != '0')) {
                    evt.consume();
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số 0 đầu tiên và bạn chỉ nhập được 10 số thôi!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            }
        });

        txt_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
                Pattern pattern = Pattern.compile(emailPattern);
                Matcher matcher = pattern.matcher(txt_Email.getText());
                if (!matcher.matches()) {
                    JOptionPane.showMessageDialog(null, "Email không hợp lệ. Vui lòng nhập lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    txt_Email.requestFocusInWindow();
                }
            }
        });
    }
    private void hienThiTextBox(int vitri)
    {
        KhachHang n = dsKH.get(vitri);
        txt_MaKH.setText(n.maKH);
        txt_TenKH.setText(n.tenKH);
        txt_DiaChi.setText(n.DiaChi);
        txt_SDT.setText(n.SDT);
        txt_Email.setText(n.Email);
        
    }
    
    private void hienThiTable()
    {
        String []Header = {"Mã Khách Hàng","Tên Khách Hàng","Địa Chỉ","SDT","Email"};
        DefaultTableModel model = new DefaultTableModel(Header,0);
        for(KhachHang n: dsKH)
        {   
            Object [] chnt = {n.maKH,n.tenKH,n.DiaChi,n.SDT,n.Email};
            model.addRow(chnt);
        }
        tbl_KH.fixTable(jScrollPane1);
        tbl_KH.setModel(model);
        tbl_KH.setRowSelectionInterval(vitri, vitri);
                
    
    }
 
    private void xoaTextBox()
    {
        txt_MaKH.setText("");
        txt_TenKH.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        txt_Email.setText("");
    }
    
    private void anHienTextbox(boolean t)
    {
        txt_MaKH.setEnabled(t);
        txt_TenKH.setEnabled(t);
        txt_DiaChi.setEnabled(t);
        txt_SDT.setEnabled(t);
        txt_Email.setEnabled(t);
    
    }
    
    private void anHienButton(boolean t)
    {
        btn_Them1.setEnabled(t);
        btn_Sua.setEnabled(t);
        btn_Luu.setEnabled(!t);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new swing.round.RoundPanel();
        lb_TenDanhMuc = new javax.swing.JLabel();
        lb_GhiChu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_MaDanhMuc = new javax.swing.JLabel();
        btn_Luu = new component.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KH = new swing.table.Table();
        lb_TenDanhMuc1 = new javax.swing.JLabel();
        lb_GhiChu1 = new javax.swing.JLabel();
        btn_Them1 = new component.Button();
        btn_Reset = new component.Button();
        btn_Sua = new component.Button();
        btn_TimKiem = new component.Button();
        txt_TimKiem = new javax.swing.JTextField();
        txt_TenKH = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_MaKH = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_TenDanhMuc.setBackground(new java.awt.Color(0, 0, 255));
        lb_TenDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_TenDanhMuc.setForeground(new java.awt.Color(255, 0, 51));
        lb_TenDanhMuc.setText("Tên khách hàng : ");

        lb_GhiChu.setBackground(new java.awt.Color(0, 0, 255));
        lb_GhiChu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_GhiChu.setForeground(new java.awt.Color(255, 0, 51));
        lb_GhiChu.setText("Địa chỉ:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN KHÁCH HÀNG");

        lb_MaDanhMuc.setBackground(new java.awt.Color(0, 0, 255));
        lb_MaDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_MaDanhMuc.setForeground(new java.awt.Color(255, 0, 51));
        lb_MaDanhMuc.setText("Mã khách hàng:");

        btn_Luu.setBackground(new java.awt.Color(238, 230, 255));
        btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_save.png"))); // NOI18N
        btn_Luu.setText("Lưu");
        btn_Luu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        tbl_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "SĐT", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_KH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_KH);

        lb_TenDanhMuc1.setBackground(new java.awt.Color(0, 0, 255));
        lb_TenDanhMuc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_TenDanhMuc1.setForeground(new java.awt.Color(255, 0, 51));
        lb_TenDanhMuc1.setText("Số điện thoại:");

        lb_GhiChu1.setBackground(new java.awt.Color(0, 0, 255));
        lb_GhiChu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_GhiChu1.setForeground(new java.awt.Color(255, 0, 51));
        lb_GhiChu1.setText("Email:");

        btn_Them1.setBackground(new java.awt.Color(238, 230, 255));
        btn_Them1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_add.png"))); // NOI18N
        btn_Them1.setText("Thêm");
        btn_Them1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them1ActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(238, 230, 255));
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_refesh.png"))); // NOI18N
        btn_Reset.setText("Làm mới");
        btn_Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(238, 230, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_edit.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_TimKiem.setBackground(new java.awt.Color(238, 230, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_search.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        txt_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TenKH.setToolTipText("");
        txt_TenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_TenKHKeyPressed(evt);
            }
        });

        txt_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SDT.setToolTipText("");
        txt_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTActionPerformed(evt);
            }
        });
        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SDTKeyPressed(evt);
            }
        });

        txt_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaKH.setToolTipText("");

        txt_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DiaChi.setToolTipText("");
        txt_DiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_DiaChiKeyPressed(evt);
            }
        });

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Email.setToolTipText("");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(btn_Them1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(btn_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(214, 214, 214))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lb_TenDanhMuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_MaDanhMuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_GhiChu)
                    .addComponent(lb_TenDanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_GhiChu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TenKH)
                    .addComponent(txt_SDT)
                    .addComponent(txt_MaKH)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Email, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(328, 328, 328))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TenDanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_GhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    private KhachHang convertTextbox_to_Obj()
       {   
           KhachHang khachhang = new KhachHang(txt_MaKH.getText(),txt_TenKH.getText(),txt_DiaChi.getText(),txt_SDT.getText(),txt_Email.getText());
           return khachhang;
       }
    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:
        KhachHang khachhang = convertTextbox_to_Obj();
        boolean hopLe = true;

    if (!kiemTraRangBuoc(khachhang)) {
        hopLe = false;
        JOptionPane.showMessageDialog(this, "Ràng buộc không hợp lệ. Vui lòng kiểm tra lại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }

    if (hopLe) {
        if (flag == 1) {
            if (kh.themKH(khachhang)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm không thành công. Vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else if (flag == 2) {
            if (kh.capNhatKH(khachhang)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật không thành công. Vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
        // Refresh data after successful operation
        flag = 0;
        kh = new DSKhachHang();
        dsKH = kh.layDanhSachKhachHang();
        hienThiTextBox(vitri);
        
        // Update table
        hienThiTable();

        btn_Luu.setEnabled(false);
        btn_Them1.setEnabled(true);
        btn_Sua.setEnabled(true);
    }
    }//GEN-LAST:event_btn_LuuActionPerformed
    private boolean kiemTraRangBuoc(KhachHang khachhang) {
    // Kiểm tra null
    if (khachhang == null || khachhang.getTenKH()== null || khachhang.getSDT() == null || khachhang.getEmail() == null) {
        return false;
    }

    // Kiểm tra ràng buộc
    String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    String tenKH = khachhang.getTenKH().trim();
    String sdt = khachhang.getSDT().trim();
    String email = khachhang.getEmail().trim();

    if (tenKH.isEmpty() || sdt.isEmpty() || email.isEmpty() || !email.matches(emailPattern)) {
        return false;
    }
    
    return true;
    }
    private void btn_Them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them1ActionPerformed
        // TODO add your handling code here:
        flag = 1;
        xoaTextBox();
        anHienTextbox(true);
        anHienButton(false);
        txt_MaKH.setEnabled(false);
        txt_MaKH.setText(kh.SinhMaKhachHang());
        //initializeMaKHField();
        RangBuocTxt();
    }//GEN-LAST:event_btn_Them1ActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        xoaTextBox();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        flag = 2;
        anHienTextbox(true);
        anHienButton(false);
        txt_MaKH.setEnabled(false);
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void tbl_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KHMouseClicked
        // TODO add your handling code here:
        vitri = tbl_KH.getSelectedRow();
        hienThiTextBox(vitri);
    }//GEN-LAST:event_tbl_KHMouseClicked

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        if (txt_TimKiem.getText()!=null)
        {
            dsKH = kh.timKiemKhachHang(txt_TimKiem.getText());
            vitri = 0;
            hienThiTable();
            hienThiTextBox(vitri);
        }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTActionPerformed

    private void txt_TenKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TenKHKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_DiaChi.requestFocus();
        }
    }//GEN-LAST:event_txt_TenKHKeyPressed

    private void txt_DiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DiaChiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_SDT.requestFocus();
        }
    }//GEN-LAST:event_txt_DiaChiKeyPressed

    private void txt_SDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDTKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_Email.requestFocus();
        }
    }//GEN-LAST:event_txt_SDTKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Button btn_Luu;
    private component.Button btn_Reset;
    private component.Button btn_Sua;
    private component.Button btn_Them1;
    private component.Button btn_TimKiem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_GhiChu;
    private javax.swing.JLabel lb_GhiChu1;
    private javax.swing.JLabel lb_MaDanhMuc;
    private javax.swing.JLabel lb_TenDanhMuc;
    private javax.swing.JLabel lb_TenDanhMuc1;
    private swing.round.RoundPanel roundPanel1;
    private swing.table.Table tbl_KH;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
