/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Class.CuaHang;
import Class.DSCuaHang;
import Class.DSDanhMuc;
import Class.DanhMuc;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Triss
 */
public class Form_NhapDanhMuc extends javax.swing.JPanel {

    /**
     * Creates new form Form_NhapSanPham
     */
    
    DSDanhMuc dm;
    ArrayList<DanhMuc> dsDanhMuc;
    DSCuaHang ch;
    ArrayList<CuaHang> dsCuaHang;
    int vitri = 0;
    int flag = 0;
    private final int tenDanhMucMaxLength = 20; // Độ dài tối đa cho tên danh mục
    private final int ghiChuMaxLength = 20; // Độ dài tối đa cho ghi chú
    public Form_NhapDanhMuc() {
        initComponents();
        dm = new DSDanhMuc();
        ch = new DSCuaHang();
        dsCuaHang = ch.layDanhSachCuaHang();
        dsDanhMuc = dm.layDanhSachDanhMuc();
        
        hienThiComboboxSP(dsCuaHang, cbo_TenCuaHang);
        hienThiTextBox(vitri);
        hienThiTable();
        anHienTextbox(false);
        anHienButton(true);
        //RangBuocText();
        //initializeMaNCCField();
    }

    public boolean tonTaiMaDanhMuc(String maDM) {
        for (DanhMuc dm : dsDanhMuc) {
            if (dm.getMaloai().equals(maDM)) {
                return true;
            }
        }
        return false;
    }
    
//    public boolean coTenGiongNhau(String tenDM) {
//        for (DanhMuc dm : dsDanhMuc) {
//            if (dm.getTenDanhMuc().trim().equalsIgnoreCase(tenDM.trim())) {
//                return true;
//            }
//        }
//        return false;
//    }
    
//    private String generateMaNCC() {
//        String autoGeneratedMaNCC = "NCC" + UUID.randomUUID().toString().substring(0, 6);
//        return autoGeneratedMaNCC;
//    }


    private void RangBuocText() {
        txt_tenDM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                String tenDM = txt_tenDM.getText().trim();
                if (txt_tenDM.getText().isEmpty() && tenDM.length() <= tenDanhMucMaxLength) {
                    JOptionPane.showMessageDialog(null, "Tên không được để trống và không vượt quá " + tenDanhMucMaxLength + " ký tự.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    txt_tenDM.setText("");
                    txt_tenDM.requestFocus();
                }
            }
        });
    }
    private void hienThiComboboxSP(ArrayList<CuaHang> ch, JComboBox<String> cbo){
        for (CuaHang chang :ch)
        {
            cbo.addItem(chang.getTench());
        }
    }
    int TimViTriCuaHang(ArrayList<CuaHang> ch , String giatri){
        for (int i = 0 ;i<ch.size();i++)
            if(ch.get(i).getMach().equalsIgnoreCase(giatri))
                return i;
        return -1;
    }
    private void hienThiTextBox(int vitri)
    {
        DanhMuc n = dsDanhMuc.get(vitri);
        txt_MaDanhMuc.setText(n.maloai);
        txt_tenDM.setText(n.Tenloai);
        String mach = n.getMach();
        int vt = TimViTriCuaHang(dsCuaHang, mach);
        if(vt!= -1 )
        cbo_TenCuaHang.setSelectedIndex(vt);
    }
    
    private void hienThiTable()
    {
        String []Header = {"Mã Danh Mục","Tên Danh Mục","Mã Cửa Hàng"};
        DefaultTableModel model = new DefaultTableModel(Header,0);
        for(DanhMuc n: dsDanhMuc)
        {   
            Object [] chnt = {n.maloai,n.Tenloai,n.mach};
            model.addRow(chnt);
        }
        tbl_DanhMucSP.fixTable(jScrollPane1);
        tbl_DanhMucSP.setModel(model);
        tbl_DanhMucSP.setRowSelectionInterval(vitri, vitri);
           
    }
    
    private void xoaTextBox()
    {
        txt_MaDanhMuc.setText("");
        txt_tenDM.setText("");
        txt_TimKiem.setText("");
    }
    
    private void anHienTextbox(boolean t)
    {
        txt_MaDanhMuc.setEnabled(t);
        txt_tenDM.setEnabled(t);
    
    }
    
    private void anHienButton(boolean t)
    {
        btn_Them.setEnabled(t);
        btn_Sua.setEnabled(t);
        btn_Xoa.setEnabled(t);
        btn_Luu.setEnabled(!t);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new swing.round.RoundPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_MaDanhMuc = new javax.swing.JLabel();
        lb_TenDanhMuc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DanhMucSP = new swing.table.Table();
        btn_TimKiem = new component.Button();
        btn_Sua = new component.Button();
        btn_Xoa = new component.Button();
        btn_Them = new component.Button();
        btn_Reset = new component.Button();
        btn_Luu = new component.Button();
        txt_tenDM = new javax.swing.JTextField();
        txt_MaDanhMuc = new javax.swing.JTextField();
        txt_TimKiem = new javax.swing.JTextField();
        lb_MaDanhMuc1 = new javax.swing.JLabel();
        cbo_TenCuaHang = new javax.swing.JComboBox<>();

        roundPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NHẬP DANH MỤC SẢN PHẨM");

        lb_MaDanhMuc.setBackground(new java.awt.Color(0, 0, 255));
        lb_MaDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_MaDanhMuc.setForeground(new java.awt.Color(255, 0, 51));
        lb_MaDanhMuc.setText("Tên cửa hàng :  ");

        lb_TenDanhMuc.setBackground(new java.awt.Color(0, 0, 255));
        lb_TenDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_TenDanhMuc.setForeground(new java.awt.Color(255, 0, 51));
        lb_TenDanhMuc.setText("Tên danh mục : ");

        tbl_DanhMucSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Mã danh mục", "Tên danh mục", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DanhMucSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_DanhMucSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhMucSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DanhMucSP);

        btn_TimKiem.setBackground(new java.awt.Color(238, 230, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_search.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(238, 230, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_edit.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(238, 230, 255));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_delete.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Them.setBackground(new java.awt.Color(238, 230, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_add.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(238, 230, 255));
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_refesh.png"))); // NOI18N
        btn_Reset.setText("Làm mới");
        btn_Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        btn_Luu.setBackground(new java.awt.Color(238, 230, 255));
        btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_save.png"))); // NOI18N
        btn_Luu.setText("Lưu");
        btn_Luu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        txt_tenDM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tenDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenDMActionPerformed(evt);
            }
        });
        txt_tenDM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tenDMKeyPressed(evt);
            }
        });

        txt_MaDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimKiemActionPerformed(evt);
            }
        });
        txt_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_TimKiemKeyPressed(evt);
            }
        });

        lb_MaDanhMuc1.setBackground(new java.awt.Color(0, 0, 255));
        lb_MaDanhMuc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_MaDanhMuc1.setForeground(new java.awt.Color(255, 0, 51));
        lb_MaDanhMuc1.setText("Mã danh mục :  ");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(btn_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(97, 97, 97))
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_TenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_MaDanhMuc1)))
                            .addComponent(lb_MaDanhMuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundPanel1Layout.createSequentialGroup()
                                .addComponent(txt_tenDM, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_MaDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                                    .addComponent(cbo_TenCuaHang, 0, 459, Short.MAX_VALUE))))
                        .addGap(245, 245, 245))))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lb_TenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_MaDanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_TenCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_MaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(txt_tenDM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_MaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TimKiem))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        if (txt_TimKiem.getText()!=null)
        {
            dsDanhMuc = dm.timKiemDanhMuc(txt_TimKiem.getText());
            vitri = 0;
            hienThiTable();
            hienThiTextBox(vitri);
        }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void tbl_DanhMucSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DanhMucSPMouseClicked
        // TODO add your handling code here:
        vitri = tbl_DanhMucSP.getSelectedRow();
        hienThiTextBox(vitri);
    }//GEN-LAST:event_tbl_DanhMucSPMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        flag = 2;
        anHienTextbox(true);
        anHienButton(false);

    // Mã danh mục sẽ không thể chỉnh sửa trong chế độ sửa
        txt_MaDanhMuc.setEnabled(false);
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        flag = 3;
        anHienButton(false);
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        flag = 1;
        xoaTextBox();
        anHienTextbox(true);
        anHienButton(false);
        // Mã danh mục sẽ không thể chỉnh sửa trong chế độ sửa
        txt_MaDanhMuc.setEnabled(false);
        txt_MaDanhMuc.setText(dm.SinhMaDanhMuc());
        RangBuocText();
    }//GEN-LAST:event_btn_ThemActionPerformed
    
    private DanhMuc convertTextbox_to_Obj()
    {   
        int vt = cbo_TenCuaHang.getSelectedIndex();
        CuaHang c =dsCuaHang.get(vt);
        DanhMuc danhmuc = new DanhMuc(txt_MaDanhMuc.getText(),txt_tenDM.getText(),c.getMach());
        return danhmuc;
    }
    
    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
         // TODO add your handling code here:
    // ẩn nút lưu, bật thêm xóa sửa,
        DanhMuc danhmuc = convertTextbox_to_Obj();

        //kiểm tra xem các textbox có rỗng không
        if (txt_tenDM.getText().isEmpty() || txt_tenDM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else {
                if (flag == 1) {
                danhmuc.setMaloai(txt_MaDanhMuc.getText());
                dm.themDanhMuc(danhmuc);
            } else if (flag == 2) {
                // Cập nhật mã danh mục từ textbox, dù nó bị mờ
                danhmuc.setMaloai(txt_MaDanhMuc.getText());
                dm.capNhatDanhMuc(danhmuc);
            } else if (flag == 3) {
                int kq= JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.YES_NO_CANCEL_OPTION);
                if(kq==JOptionPane.YES_OPTION) {
                    dm.xoaDanhMuc(danhmuc);
                    //vitri = vitri - 1;
                }
            }

                flag = 0;
                dm = new DSDanhMuc();
                dsDanhMuc = dm.layDanhSachDanhMuc();
                hienThiTextBox(vitri);
                hienThiTable();

                btn_Luu.setEnabled(false);
                btn_Them.setEnabled(true);
                btn_Sua.setEnabled(true);
                btn_Xoa.setEnabled(true);
        }
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void txt_tenDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenDMActionPerformed

    private void txt_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimKiemActionPerformed
        // TODO add your handling code here:
        if (txt_TimKiem.getText()!=null)
        {
            dsDanhMuc = dm.timKiemDanhMuc(txt_TimKiem.getText());
            vitri = 0;
            hienThiTable();
            hienThiTextBox(vitri);
        }
    }//GEN-LAST:event_txt_TimKiemActionPerformed

    private void txt_TimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKiemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimKiemKeyPressed

    private void txt_tenDMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tenDMKeyPressed
        // TODO add your handling code here:
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
//            txt_GhiChu.requestFocus();
//        }
    }//GEN-LAST:event_txt_tenDMKeyPressed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        xoaTextBox();
    }                       


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Button btn_Luu;
    private component.Button btn_Reset;
    private component.Button btn_Sua;
    private component.Button btn_Them;
    private component.Button btn_TimKiem;
    private component.Button btn_Xoa;
    private javax.swing.JComboBox<String> cbo_TenCuaHang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_MaDanhMuc;
    private javax.swing.JLabel lb_MaDanhMuc1;
    private javax.swing.JLabel lb_TenDanhMuc;
    private swing.round.RoundPanel roundPanel1;
    private swing.table.Table tbl_DanhMucSP;
    private javax.swing.JTextField txt_MaDanhMuc;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_tenDM;
    // End of variables declaration//GEN-END:variables

}
